### ISSUE TITLE
android/run_ui_tests isn't running: pre_test_command, pre_emulator_wait_steps or pre_run_tests_steps

### ISSUE THREAD

**Issue by Brunobrlk** [CircleCI-Public/android-orb#114]
# Version 3.1.0
**Problem:** I'm trying to execute a setup script before running instrumented tests, but the job is failing because some local files are missing due to the script not running before the tests.
**Expected result:** Run ./setup_environment or any command/step before running ui tests

Full code: https://github.com/Brunobrlk/Scoreboard
```
orbs:
  android: circleci/android@3.1.0

workflows:
  full-pipeline:
    jobs:
      - lint
      - unit-tests
      - android/run_ui_tests:
          executor:
            name: android/android_machine
            resource_class: large
            tag: default

          pre_test_command: 'chmod +x setup_environment && ./setup_environment'

          pre_emulator_wait_steps:
            - run:
                name: Setupbrlk
                command: |
                  chmod +x setup_environment
                  ./setup_environment

          pre_run_tests_steps:
            - run:
                name: Setupbrlk
                command: |
                  chmod +x setup_environment
                  ./setup_environment

          matrix:
            parameters:
              system_image:
                - system-images;android-30;default;x86_64
                - system-images;android-29;default;x86_64
          name: ui-tests-<<matrix.system_image>>

```

Output Screenshot:

![Image](https://github.com/user-attachments/assets/be7ea37f-89c3-4f8e-b338-4bd6e108b55f)

**Comment by marboledacci** [comment]
The problem here is that all the pre_steps you have defined are run after the assembleDebugAndroidTest. The first to run is `pre_emulator_wait_steps` which is immediately after that.
If you don't need that assemble, you can set `post_emulator_launch_assemble_command` to empty string and it won't run.

If you need that you have two options.
1. You can combine in the `post_emulator_launch_assemble_command` the default command (./gradlew assembleDebugAndroidTest) with your script execution. Something like `chmod +x setup_environment && ./setup_environment && ./gradlew assembleDebugAndroidTest`
2. The job `run_ui_tests` is just a combination of the command `start_emulator_and_run_tests` wtih a checkout. You can create your own job setting your command after the checkout and before `start_emulator_and_run_tests`. Something like this:
```yaml
steps:
      - checkout
      - run: |
          chmod +x setup_environment
          ./setup_environment
      - android/start_emulator_and_run_tests:
          system_image: system-images;android-30;default;x86_64
```

The choice depends on when you want you want your script to run. The first option will run your script after the gradle cache step. The second option will run your script after cloning your repo.

If you want even more control on the order of the steps, you can create the job with the individual commands that compose `start_emulator_and_run_tests`.

The current order of the job `run_ui_tests` in terms of atomic commands or steps is:
- checkout
- create_avd
- start_emulator
- restore_gradle_cache (conditional)
- post_emulator_launch_assemble_command (conditional based on the command passed)
- pre_emulator_wait_steps (conditional based on the command passed)
- wait_for_emulator (conditional)
- adb logcat (conditional)
- disable_animations (conditional)
- post_emulator_wait_steps (conditional based on the steps passed)
- pre_run_tests_steps (conditional based on the steps passed)
- run_tests
- post_run_tests_steps (conditional based on the steps passed)
- save_gradle_cache (conditional)
- kill_emulators (conditional)
