### ISSUE TITLE
Options "no-output-timeout" not being used by run-tests command

### ISSUE THREAD

**Issue by msfstef** [CircleCI-Public/android-orb#70]
### Orb version
2.2.0

### What happened
Added `no-output-timeout` parameter to `start-emulator-and-run-tests` and noticed that it still timed out at 10m despite having it set to 1h.

Example:
```
- android/start-emulator-and-run-tests:
          avd-name: android-phone-32
          additional-avd-args: "-d pixel_6"
          system-image: system-images;android-32;google_apis;x86_64
          no-output-timeout: 1h
          ...etc
```

### Expected behavior
Should actually set the no output timeout of the test command.

### Proposed solution
Created a small PR #69  to solve this as it seems that the `no-output-timeout` parameter from `start-emulator-and-run-tests` is being passed to `run-tests`, but `run-tests` is not actually setting it on the command running the run-tests script.
