### ISSUE TITLE
pre-test-command gets error `environment: line 8: mvn: command not found`

### ISSUE THREAD

**Issue by thaole-NRS** [CircleCI-Public/android-orb#78]
### What happened

I got error when using `pre-test-command`
My config.yml step:
```
      - android/run-tests:
          max-tries: 1
          pre-test-command: source /etc/environment
          test-command: mvn clean test -DxmlFile=testngCompileCode.xml
```
CircleCI: https://app.circleci.com/pipelines/github/checkout51/c51-mobile-automation/1962/workflows/66f134f6-60fd-4e6d-9457-93d398acfe4e/jobs/6818

Error in CircleCI:
```
Starting test attempt 1
environment: line 8: mvn: command not found
Max tries reached (1)

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior
`pre-test-command: source /etc/environment` should work

**Comment by ryanbourdais** [comment]
Hi @thaole-NRS I'm looking into this issue right now.

**Comment by ryanbourdais** [comment]
Hi @thaole-NRS the orb seems to be working as intended, this is evident from it erroring out with `environment: line 8: mvn: command not found`. It seems that the issue comes from sourcing `/etc/environment` which is not advised as it can have unintended consequences such as this. I am closing this issue with this response, but if you need any further help or explanation you are more than welcome to reopen this issue.

**Comment by thaole-NRS** [comment]
@ryanbourdais You're correct, it is functioning as intended. I refrain from utilizing the 'source /etc/environment' command. Prior to executing the 'test-command,' I aim to establish an environment variable named TESTFILES, which should obtain its value from a file called 'testfiles.txt.' Could you assist me in determining the appropriate command for the 'pre-test-command' phase?

**Comment by ryanbourdais** [comment]
If the value of the environment variable needs to be set dynamically we typically would create local variables like this using shell commands
```shell
- run: echo 'export STR="string"' >> "$BASH_ENV"
- run: echo ${STR}
``` 
this would set create the local environment variable `STR` which is accessible in a later step.
In the event that the value is known and fairly static you can use an [environment variable](https://circleci.com/docs/env-vars/#example-configuration-of-environment-variables)

**Comment by thaole-NRS** [comment]
```
- run:
    name: Run E2E Mobile Tests
    command: |
      echo "export TESTFILES=$(circleci tests glob "features_iOS/*.feature" | circleci tests split --split-by=filesize | xargs)" >> "$BASH_ENV"
      echo ${TESTFILES}
      [ -n "$TESTFILES" ] || exit 1
- run:
    name: "What was my custom environment variable?"
    command: echo ${TESTFILES}
- android/run-tests:
    max-tries: 1
    pre-test-command: echo ${TESTFILES}
```
@ryanbourdais The `run` command with "What was my custom environment variable?" returns with the expected value. But the `pre-test-command` returns with `${TESTFILES}` which means it doesn't know `TESTFILES` env, did I miss anything here?
