### ISSUE TITLE
Job rejected because resource class doesn't exist for android-machine with latest orb version

### ISSUE THREAD

**Issue by PetarKaukov** [CircleCI-Public/android-orb#86]
### Orb version

2.3.0

### What happened

I wanted to upgrade all of our CI executor images to the newest ones. When specifying version `2023.10.2`, CircleCI fails with the error:
`Job was rejected because resource class xlarge, image android:2023.10.2 is not a valid resource class `. 

This happens only for the `android-machine` executor; `android-docker` runs with this version.

As per the official docs, both `android-docker` and `android-machine` support the resource class and many others:

https://circleci.com/developer/orbs/orb/circleci/android#executors-android-docker

https://circleci.com/developer/orbs/orb/circleci/android#executors-android-machine

After testing more, all versions after `2023.08.1` fail in the same exact way. The resource class just doesn't exist for the later images.

### Expected behavior

The CI pipelines should run normally without any errors.

### Our config (the important parts)

```yml
version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
    android-test:
      executor:
        name: android/android-machine
        resource-class: xlarge
        tag: 2023.10.2
```

Here's the excerpt from the official docs:
```yml
parameters:
  resource-class:
    default: medium
    description: Resource class used for the executor.
    enum:
      - small
      - medium
      - medium+
      - large
      - xlarge
      - 2xlarge
      - 2xlarge+
    type: enum
  tag:
    description: >
      The Android image tag to use.

      Choose a tag from
      https://circleci.com/developer/images/image/cimg/android#image-tags.
    type: string
```
